name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.0

    - name: Build
      run: go build -o main .

    - name: Run tests
      run: go test ./...

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t username/go-rate-limiting-cors-api:${{ github.sha }} .
        docker push username/go-rate-limiting-cors-api:${{ github.sha }}

    - name: Tag the Docker image with 'latest'
      run: |
        docker tag username/go-rate-limiting-cors-api:${{ github.sha }} username/go-rate-limiting-cors-api:latest
        docker push username/go-rate-limiting-cors-api:latest
