name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      working-directory: ../../cmd  
      run: go build -o main ../../cmd/main.go

    - name: Run tests
      working-directory: ../../cmd  
      run: go test ../../...
